/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class table_Cell */

#ifndef _Included_table_Cell
#define _Included_table_Cell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     table_Cell
 * Method:    calculateFormula
 * Signature: (Ljava/lang/String;Ljava/lang/String;[CII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_table_Cell_calculateFormula
  (JNIEnv *, jobject, jstring, jstring, jcharArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
